AllCops:
  TargetRubyVersion: "2.3"

# Use double quotes
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false
