version: '3'
services:
  db:
    image: container-registry.oracle.com/database/express:latest
    volumes:
      - db:/opt/oracle/oradata
    environment:
      - ORACLE_PWD=thisisonlyusedlocally
    ports:
      - "127.0.0.1:1521:1521"
      - "127.0.0.1:5500:5500"
  gem:
    build: .
    volumes:
      - .:/app
    environment:
      - TERM=dumb
    stdin_open: true
    tty: true
    depends_on:
      - db
volumes:
  db:
