version: '3'
services:
  db:
    image: store/oracle/database-enterprise:12.2.0.1
    volumes:
      - db:/ORCL
    ports:
      - 1521:1521
  gem:
    build: .
    volumes:
      - .:/app
    environment:
      - TERM=dumb
    stdin_open: true
    tty: true
    depends_on:
      - db
volumes:
  db:
