name: CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Start containers
      run: docker-compose up -d
    - name: Wait for Oracle to become available
      run: sleep 120
    - name: Check containers
      run: docker-compose ps
    - name: Run tests
      run: docker-compose exec -T gem rspec
